


import GUI.ShowUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zhen
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
int windowWidth = this.getWidth(); //获得窗口宽

int windowHeight = this.getHeight(); //获得窗口高

Toolkit kit = Toolkit.getDefaultToolkit(); //定义工具包

Dimension screenSize = kit.getScreenSize(); //获取屏幕的尺寸

int screenWidth = screenSize.width; //获取屏幕的宽

int screenHeight = screenSize.height; //获取屏幕的高

this.setLocation(screenWidth / 2 - windowWidth / 2, screenHeight / 2 - windowHeight / 2);//设置窗口居中显示
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("请输入源文件路径");

        jButton1.setText("开始转换");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton2.setText("清空");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jButton1))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dir = null;
        this.spaceTime = 0;
        jTextField1.setText(null);
        jTextField1.grabFocus();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // 传递源文件的路径给它
        String path = this.jTextField1.getText().trim();
        System.out.println("path:" + path);
        //路径合法性判断
        //这种情况是为了避免用户直接复制windows的路径例如:C:\Windows\System32\cmd.exe导致的路径异常。
        System.out.println("formatted:"+PdfToWord.formatpathString(path));
        path = PdfToWord.formatpathString(path);
        //启动main函数
        String res = new Main().main(new String[]{path});
        if(res.equals("转换成功")){
            ShowUtils.message(res);
        }else{
            ShowUtils.errorMessage(res);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    int spaceTime = 0;
    private File dir = null; 
    private ArrayList<File> files = null;
    //每当输入文字时就会触发这个函数
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
         
        if(evt.getKeyChar() == evt.VK_SPACE){
             if(new File(this.jTextField1.getText()).isDirectory() || (new File(this.jTextField1.getText()).isFile() && files != null) ){
                   //如果是第1次粘贴，将文件放到集合中去。
                   spaceTime ++;//按下了空格键，space次数+1
                   if(dir == null){
                       dir = new File(this.jTextField1.getText());
                       files = new ArrayList<>();
                       for(File f:dir.listFiles()){
                           if(f.isFile()){
                               files.add(f);
                           }
                       }
                   }
                   //取得集合里面的文件，如果超出了再转一圈。
                   String fileName = files.get(spaceTime%files.size()).getName();
                   if(new File(jTextField1.getText()).isFile()){
                       jTextField1.setText(jTextField1.getText().substring(0,jTextField1.getText().lastIndexOf("\\")+1) + fileName);
                       System.out.println("EditText:" + jTextField1.getText().substring(0,jTextField1.getText().lastIndexOf("\\")+1) + fileName);
                   }else if(new File(jTextField1.getText()).isDirectory()){
                       jTextField1.setText(jTextField1.getText() + "\\" + fileName);
                       System.out.println("EditText:" + jTextField1.getText() + "\\" + fileName);
                   }
                   
             }

            
        }
        //如果敲了Enter键，则触发和button一样的操作。
        if(evt.getKeyChar() == evt.VK_ENTER){
                 // 传递源文件的路径给它
                String path = this.jTextField1.getText();
                //路径合法性判断
                //这种情况是为了避免用户直接复制windows的路径例如:C:\Windows\System32\cmd.exe导致的路径异常。
                System.out.println("formatted:"+PdfToWord.formatpathString(path));
                path = PdfToWord.formatpathString(path);
                //启动main函数
                String res = new Main().main(new String[]{path});
                if(res.equals("转换成功")){
                    ShowUtils.message(res);
                }else{
                    ShowUtils.errorMessage(res);
                }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
